# Generated by Django 5.2.9 on 2025-12-04 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название заявки')),
                ('description', models.TextField(max_length=150, verbose_name='Описание заявки')),
                ('image', models.FileField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'), verbose_name='Загрузите фото заявки')),
                ('status', models.CharField(choices=[('N', 'Новая'), ('P', 'Принято в работу'), ('D', 'Выполнено')], default='N', max_length=1, verbose_name='Статус заявки')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата создания заявки')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('category', models.ForeignKey(default='O', on_delete=django.db.models.deletion.CASCADE, to='design.category', verbose_name='Категория заявки')),
            ],
        ),
    ]
