# Generated by Django 5.2.9 on 2025-12-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_category_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.category', verbose_name='Категория заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(verbose_name='Описание заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.FileField(upload_to='applications/', verbose_name='Загрузите фото заявки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название категории', max_length=150, verbose_name='Название'),
        ),
    ]
