# Generated by Django 5.2.9 on 2025-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_alter_application_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name='Загрузите фото заявки'),
        ),
    ]
