# Generated by Django 5.2.9 on 2025-12-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_alter_application_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='design_image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Фото готового дизайна'),
        ),
    ]
