# Generated by Django 5.2.9 on 2025-12-05 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_application_design_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заявке'),
        ),
        migrations.AddField(
            model_name='application',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Добавить в избранное'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='application',
            name='design_image',
            field=models.FileField(blank=True, null=True, upload_to='designs/', verbose_name='Фото готового дизайна'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.FileField(upload_to='applications/', verbose_name='Загрузите фото заявки'),
        ),
    ]
